# Generated by Django 4.2.7 on 2023-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cidade',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='cpf',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='endereco',
            field=models.CharField(default='0', max_length=70),
        ),
        migrations.AddField(
            model_name='student',
            name='matricula',
            field=models.CharField(default='0', max_length=14),
        ),
        migrations.AddField(
            model_name='student',
            name='nascimento',
            field=models.DateField(default='2000-01-01', max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='serie',
            field=models.CharField(default='0', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='telefone',
            field=models.CharField(default='0', max_length=14),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
